logging:
  config:
    E:\学习资料\项目\demo\src\main\resources\logback.xml
  level:
    com.example.demo.dao: trace

#配置微服务的路径
url:
  #订单服务路径
  orderUrl: https://localhost:8002
  #购物车服务路径
  shopUrl: https://localhost:8003


#数据库连接
datasource:
  url: 120.79.95.178:3306/mysql_zjc

spring:
  thymeleaf:
    cache: false  #关闭thymeleaf的自动缓存
  datasource: # 数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: root
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000
  #redis相关配置
  redis:
    database: 5
    # 配置redis的主机地址，需要修改成自己的
    host: 120.79.95.178
    port: 6379
    password: 123456
    timeout: 5000
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 500
        # 连接池中的最小空闲连接，默认值也是0。
        min-idle: 50
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-active: 1000
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 2000


mybatis:
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范
    mapper-locations: # mapper映射文件位置
      classpath:mapper/*.xml
